import { useState, React } from 'react';
import axios from 'axios';
import Head from 'next/Head';
import styles from "../styles/Home.module.css";


const App = () => {
  const [company, setCompany] = useState('');
  const [name, setName] = useState('');
  const [skills, setSkills] = useState('');
  const [result, setResult] = useState('');
  const [position, setPosition] = useState('');
  const [experience, setExperience] = useState('');
  const [isloading, setIsloading] = useState(false);
  const [error, setError] = useState(null);

  const data = {
    company,
    name,
    skills,
    position,
    experience
  }


  async function handleSubmit(e) {
    e.preventDefault()
    setIsloading(true);

    const result = await axios.post('/api/generate', data).catch(err => { setError(err); });

    setResult(result.data);
    setIsloading(false);
  }

  function CopyButton({ text }) {
    const handleClick = () => {
      navigator.clipboard.writeText(text);
    };

    return <p style={{ fontSize: '13px' }} onClick={handleClick}>Copy to Clipboard</p>;
  }

  return (
    <>
      <Head>
        <title>Generate Cover Letter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.container}>
        <div className={styles.wrapper}>
          <header className={styles.header}>
            <p>Generate a <span>Cover Letter</span> in seconds.</p>
          </header>
          <form className={styles.form} onSubmit={(e) => { handleSubmit(e) }}>
            <label>Company:</label>
            <input type='text' required onChange={(e) => { setCompany(e.target.value) }} />

            <label>Name:</label>
            <input type='text' required onChange={(e) => { setName(e.target.value) }} />

            <label>Position:</label>
            <input type='text' required onChange={(e) => { setPosition(e.target.value) }} />

            <label>Skills:</label>
            <textarea type='text' required placeholder='Outline all your skills' onChange={(e) => { setSkills(e.target.value) }} />

            <label>Years of Experience:</label>
            <input type='number' required onChange={(e) => { setExperience(e.target.value) }} />

            <button className={styles.button} type='submit'>Submit</button>
          </form>
          <div className={styles.result}>
            <div className={styles.copy}>
              {result && <CopyButton text={result} />}
            </div>
            {isloading ? <p>Generating cover letter...</p> : <span style={{ whiteSpace: "pre-wrap" }}> {result}</span>}
          </div>
        </div>
      </div>
    </>
  )
}


export default App;